services:
  assistant:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: PrezHelper
    volumes:
      - ./app:/app
      - ./data:/app/data
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run web_prezhelper.py --server.port 8501 --server.address 0.0.0.0
    working_dir: /app
