services:
  assistant:
    build: .
    container_name: PrezHelper
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./chroma:/app/chroma
    ports:
      - "8501:8501"  # Streamlit web interface
    environment:
      - PYTHONUNBUFFERED=1
      - LANGCHAIN_TRACING_V2=false
      - CHROMA_DB_DIR=/app/chroma
    command: streamlit run app/web_prezhelper.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    # Optionnel : pour pré-télécharger le modèle mistral au démarrage
    entrypoint: ["/bin/bash", "-c", "ollama serve & sleep 2 && ollama pull mistral && tail -f /dev/null"]

volumes:
  ollama_data:

# Astuce :
# Les volumes permettent de modifier le code source (./app) et les données (./data) sur votre machine locale
# et de voir les changements instantanément dans le conteneur, sans avoir à reconstruire l'image Docker.
# Cela accélère le développement et facilite le débogage.
