version: "3.9"
services:
  assistant:
    build: .
    container_name: PrezHelper
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./chroma:/app/chroma
    ports:
      - "7860:7860"  # si Gradio ou FastAPI
    environment:
      - PYTHONUNBUFFERED=1
      - LANGCHAIN_TRACING_V2=false
      - CHROMA_DB_DIR=/app/chroma

# Astuce :
# Les volumes permettent de modifier le code source (./app) et les données (./data) sur votre machine locale
# et de voir les changements instantanément dans le conteneur, sans avoir à reconstruire l'image Docker.
# Cela accélère le développement et facilite le débogage.
