# Image de base légère
FROM python:3.10-slim

# Installer les bibliothèques système nécessaires (adapter si besoin)
RUN apt-get update && apt-get install -y \
    libglib2.0-0 libsm6 libxrender1 libxext6 libgl1 \
    && rm -rf /var/lib/apt/lists/*

# Dossier de travail dans le conteneur
WORKDIR /app

# Copier uniquement le fichier de dépendances
COPY requirements.txt .

# Installer pip + dépendances Python
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Rien d'autre : le code source sera monté via `volumes` dans docker-compose
